#插件会检测玩家的权限并判断这个玩家的权限是否超出了普通权限组的权限时,被处理指令的内容
处理指令:
  - 'bc §c玩家: %player_name% 权限有问题!'
  - 'ban %player_name% §c你的权限有问题!' #或者 'kick %player_name% §c你的权限有问题!'
#普通的玩家用的权限组(有vip也需要,只要是个非管理员的都写)
非管理组:
  - 'default'
  - 'vip1'
  - 'vip2'
不检测的玩家: ##OP记得加进来
  - 'TestPlayer'